### ISSUE TITLE
List of docs that have Intros

### ISSUE THREAD

**Issue by Conal-Tuohy** [IUBLibTech/newton_chymistry#1]

**Comment by Conal-Tuohy** [comment]
Is this just about generating a page that links to all the intros?

**Comment by mdalmau** [comment]
Some manuscripts have critical introductions: https://webapp1.dlib.indiana.edu/newton/mss/intro/ALCH00200/ (see browse view from screen grab as well). Wally Hooper was going to generate a list of those for you so I think those are instructions for him!  I'll have to double check the original reqs. doc. For your purposes, mss with intros need to have a link in the results. In the full text view of the intro, the user should be able to access the normalized and diplomatic versions of the ms. 
<img width="927" alt="Screen Shot 2019-04-24 at 8 39 14 AM" src="https://user-images.githubusercontent.com/573273/56660153-e66e4c00-666c-11e9-8621-a80988e3cda5.png">

**Comment by Conal-Tuohy** [comment]
Oh OK, so the "list" is not a feature of the website, then?

**Comment by Conal-Tuohy** [comment]
I think this is the XPath to use:

```xpath
/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msContents/msItem/note[@type='introduction']
```
