### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by Conal-Tuohy** [IUBLibTech/newton_chymistry#10]
- Maintain an Advanced Search option with Boolean for Keyword and Title
- Offer "on-screen keyboard" for searching alchemical characters
- Filter advanced search with pre-populated lists (i.e. facets), e.g.
  - Institution

**Comment by Conal-Tuohy** [comment]
Example metadata
```
ALCH00001
	alt-id w/idno:	Keynes MS. 12
	  institution:	Cambridge University
	   repository:	King's College Library
	   collection:	Keynes
```

**Comment by Conal-Tuohy** [comment]
Facets added in ea776b7 and 005c604

**Comment by mdalmau** [comment]
Emailed the team on 8 Dec 2019

---------
Hi, all,

Please review the way the search / advanced search is implemented on the new site:
https://newton.dlib.indiana.edu/

The keyword search persists across the banner with the exception for “Browse Mss” because that page is both the A-Z browse list and also the advanced search page.  The current site separates those two  functions, but that’s an XTF out-of-box imposition.  I think it’s  fine for them to be combined.  

Thoughts?

Thanks,
Michelle

**Comment by mdalmau** [comment]
Based on  the email the team sent (see below), the pending issues:

1) Wildcard searching does not appear to be supported.  Is this correct?  The current web site supports * searches and would like to see the carry through of this functionality.

2) Does the advanced search support Boolean searching like the existing web site?  

3)  Underneath the search box, the 'nn results' message/title[?] in the same size type as 'Search' above the box can be confusing for the user who followed 'Browser Mss' to get here. Maybe 'nn documents' would be better for that user while the 'nn results' message is appropriate after a search button has been clicked and a search result returned? Could 'nn documents' work for both users?

> Hello,
> 
> We spent some time working with the Search and Browse Mss features and results.
> 
> We like the faceted search, and how the list of facets available on the left updates when a user search returns a list of search results, presumably to show which facets are available in that subset of returned documents.
> 
> We love the integration of the symbols, which I think we've mentioned before.
> 
> We tried using wildcard searches, like 'green l*on' and 'green l*', which we thought would return locations with 'green lyon' or 'green lion', but got the 'No results' page. Are there wildcard searches?
> 
> Combining the 'Browse manuscripts' and 'Advanced search' or using 'Browse' as the basis for 'Advanced search' seems fine, but what is the difference? Under 'Advanced search' the current live site will try to support extra conditions with Boolean searches on other fields. Are those available here?
> 
> The new page layout on the Browse Mss/Advanced search page places the label 'Search' at the top, which is reasonable. Whether the user just clicked 'Browse Mss' to page through the titles, or 'Advanced search' to start a search, having the search box mechanism at the top is intuitive.
> 
> However, underneath the search box, the 'nn results' message/title[?] in the same size type as 'Search' above the box can be confusing for the user who followed 'Browser Mss' to get here. Maybe 'nn documents' would be better for that user while the 'nn results' message is appropriate after a search button has been clicked and a search result returned? Could 'nn documents' work for both users?
> 
> What do you think?
> 
> I think we're all feeling good about the look and feel and operations of new site, so we seem to be confident that we can work with the new framework going forward.

```

**Comment by mdalmau** [comment]
I don't think these issues are outstanding so I will close.
