### ISSUE TITLE
Rendering issue when <note type="biblio"> is used

### ISSUE THREAD

**Issue by tubesoft** [IUBLibTech/newton_chymistry#106]
I found out that when we use `<note type="biblio">`, it renders a line break. I also found the reason for that. `<note>` tag was rendered outside popup as well as inside it in HTML.

To suppress the `<note>` tag outside, I changed line 234 of `p5-to-html.xsl` into 
`<xsl:template mode="create-content" match="*[not(note[@type='biblio'])]">` 
from `<xsl:template mode="create-content" match="*">`

In my local environment, this fix seems to work fine. I am making a note here for the code review later.

**Comment by tubesoft** [comment]
Since the fix previously explained seemed to create more bugs, I changed line 477 instead.

**Comment by wehooper** [comment]
Issue has been resolved.
