### ISSUE TITLE
<sic> on repeated words not working in Chrome

### ISSUE THREAD

**Issue by aewingate** [IUBLibTech/newton_chymistry#109]
Jim and I found today that erroneously repeated words encoded with `<sic n="rep">` are not rendering in Carbon correctly in either the diplomatic or the normalized versions.

In the diplomatic, mousing over the highlighted text should create a pop-up that says "erroneous repetition". Nothing shows up right now. 
![image](https://user-images.githubusercontent.com/72820848/124652205-d61ba380-de69-11eb-8ef6-1ca093ddfb58.png)

In the normalized, the second ampersand should disappear, but instead it looks exactly the same as the diplomatic (the highlighted `<sic>` is still there as well. 

The issue is happens in Carbon on Chrome, Firefox, and Edge. 
The live site works fine on all browsers:
![image](https://user-images.githubusercontent.com/72820848/124652446-2561d400-de6a-11eb-9730-0301e49e5389.png)
![image](https://user-images.githubusercontent.com/72820848/124652462-2b57b500-de6a-11eb-9d3a-4ee5839c2caf.png)

This particular example is found in ALCH00062, f. 3r which is line 789 in the TEI, but it happens elsewhere too (e.g. ALCH00055, f. 2v with the word "of")

**Comment by tubesoft** [comment]
It is actually duplicated with #94, and hopefully, it will be fixed in the next deployment.
