### ISSUE TITLE
Mouseover pop-up feature found in cross-referencing links in footnotes

### ISSUE THREAD

**Issue by tubesoft** [IUBLibTech/newton_chymistry#114]
Mouseover pop-up feature found in cross-referencing links in footnotes like the following has a rendition issue as mentioned in [this Alex's post](https://github.com/IUBLibTech/newton_chymistry/issues/112#issuecomment-963221796). In the meeting, we decided to remove this feature to avoid confusion. I will deal with it.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/17519127/141018142-92a72018-6959-4372-bece-2d9940299c55.png">
<img width="814" alt="image" src="https://user-images.githubusercontent.com/17519127/141018187-c05aa6d9-496e-4e5a-94e0-c4882b7687be.png">

**Comment by wehooper** [comment]
Issue is resolved.
