### ISSUE TITLE
Show search results as "brief view"

### ISSUE THREAD

**Issue by Conal-Tuohy** [IUBLibTech/newton_chymistry#12]
Default results display should be a "brief view" as seen on the web site with an option to view the "full view".

![newton-results](https://user-images.githubusercontent.com/1264711/56641235-3faf9d00-66b8-11e9-860a-cf765c3df576.png)

**Comment by Conal-Tuohy** [comment]
There are still some issues here with the titles of the texts; they are not consistent

**Comment by Conal-Tuohy** [comment]
updated to show a partial set of metadata with an expansion to show the full set in revision 3eb258c2a34dd976b00cb7c74de3113770279050

**Comment by mdalmau** [comment]
I emailed the Newton team on 8 Dec 2019 for their feedback.

------
Please take a look at the brief results view on the new Newton site:

https://newton.dlib.indiana.edu/

It looks fantastic to me and am happy to close GitHub issue if y’all agree.  The Matches also looks and works great.  

While you are there, have a look at the full metadata display as well.  

I see some wonky spacing issues, but nothing critical.  For example, measurements and watermarks labels are indented but info that pertains to each is not.  

Sometimes there’s a line space between labels and sometimes not.  I would prefer a line space between chunks of discrete metadata, but again not a deal break.  

If you agree with some of this look/feel stuff, let me know.  I can add to a punch list, but again, it may not get addressed before we launch.

Thanks,
Michelle

**Comment by mdalmau** [comment]
According to email sent Acco

**Comment by mdalmau** [comment]
According to email sent on 12/13/2019 this issues can be closed.
