### ISSUE TITLE
Extra space before disjunctive lists

### ISSUE THREAD

**Issue by aewingate** [IUBLibTech/newton_chymistry#120]
While Jim and I were reviewing ALCH00063-05 (5.4v towards the very bottom), we noticed that there was extra space being inserted before disjunctive lists in the document that aren't present in the manuscript and there's no extra space added in the encoding itself. 

Here's what it looks like in possum (port 8180):
![image](https://user-images.githubusercontent.com/72820848/152652644-3c32aef2-5f8f-4d9a-82ad-76e3a4e613de.png)

Here's the manuscript:
![image](https://user-images.githubusercontent.com/72820848/152652651-6606b2c6-0e88-4577-8140-453939f27047.png)

And here's the encoding (with the lists highlighted)
![image](https://user-images.githubusercontent.com/72820848/152652671-3e9416cb-4733-4158-86e5-d1d65fee97da.png)

Is there some way to remove this extra whitespace before the lists? Let me know if you need more information.

**Comment by tubesoft** [comment]
Yes, it is an easy job! I added a negative margin (2em) on the left side. And becomes like this:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/17519127/152853465-0dfa4fda-68a9-4670-b2c4-5ea473898832.png">

**Comment by aewingate** [comment]
Awesome that's perfect! Thank you, Takatomo!

**Comment by wehooper** [comment]
Those spaces have been removed.
