### ISSUE TITLE
3-way citation in ALCH00046

### ISSUE THREAD

**Issue by aewingate** [IUBLibTech/newton_chymistry#123]
I had forgotten to input this issue in Github from quite a while ago, but this is the citation where the citation itself is "Basilius", but the information appears to be 3 different statements taken from 2 different sources:
![image](https://user-images.githubusercontent.com/72820848/160250204-8aa55d09-299d-45ab-aa72-f68313be2880.png)
1. is from #Basilius_Valentinus1657, ch. 15-16, 29
2. is from #Basilius_Valentinus1657, p. 8 in a much later section (that has its own pagination)
3. is from the words around the illustration at the end of ALCH00052

In normal circumstances if there was only one source, we'd put a `<bibl>` around "Basilius" and have the corresp point to that one source. But I don't imagine we can have two corresp values in one bibl. 

I talked to John Walsh, and he suggested using `<span>` around the different sections, though he encouraged looking at the TEI to see if there was something more specific. I think `<quote>` could serve too. So in that solution, we'd add our cert/corresp/notes to each `<span>` or `<quote>`. But I assume that would require some messing with XSLT and other things to get that to render well. 

Another solution could be to encode "Basilius" with one bibl and link to #Basilius_Valentinus1657 there while having a note dedicated to explaining 1 and 2 of the citation, and then put another bibl right in front of 3 without adding anything into the content of the bibl (e.g., like Basilius in the first bibl), but still have the corresp, cert, and note in this second bibl that talk about ALCH00052. 
This is what I mean:
![image](https://user-images.githubusercontent.com/72820848/160250966-887f99b5-1a68-475a-b0b4-79112f077802.png)

This may be something to talk more about on the next Tuesday meeting, but I wanted to bring it up here since solution 1 would need rendering help.

**Comment by tubesoft** [comment]
My idea is to create empty `<bibl>` elements at 2 and 3 in the picture above.
Either `<bibl corresp="xxx" cert="yyy"></bibl>` or `<bibl corresp="xxx" cert="yyy"/>` should render a bibl icon for the pop-up. We might also be able to add a `<note type="biblio">` element in it to add some note to explain the emptiness.

**Comment by mdalmau** [comment]
@aewingate : Why not have 3 bibls?

**Comment by aewingate** [comment]
@mdalmau, the reason to not do bibls or do empty `<bibl>`s is because there's no author name, title, or page number in 2 and 3. We'd be putting a bibl around the cited material instead of the citation itself if we didn't do the empty `<bibl>`s

**Comment by jawalsh** [comment]
I don't know if this solves the problem, but you can have multiple `@corresp` values, e.g.,:

```xml
<bibl corresp="#source1 #source1 #source2">Basilius</bibl>
```

Alternatively, this may be helpful.

```xml
<p>
<bibl xml:id="origBibl" corresp="#source1">Basilius</bibl>Et d'abord, bourdonnement dans les oreilles, 
éblouissement dans les yeux. Au-dessus de nos têtes une double voûte en ogive, lambrissée en sculptures 
de bois, peinte d'azur, fleurdelysée en or; sous nos pieds, un pavé alternatif de marbre blanc et noir. 
<bibl sameAs="#origBibl" corresp="#source1"/> À quelques pas de nous, un énorme pilier, puis un autre,
 puis un autre;  <bibl sameAs="#origBibl" corresp="#source2"/> en tout sept piliers dans la longueur 
de la salle, soutenant au milieu de sa largeur les retombées de la double voûte.
</p>
```

Although the `@sameAs` suggests the `Basilius` would be present, even though the `bibl` elements are empty, because they should be the "same as" the element they are pointing to, with the original's child text, etc. There is also the similar `@copyOf` attribute, but it's not clear to me without further reflection which if any of these two attributes might be appropriate.

**Comment by aewingate** [comment]
Resolved by using 2 bibls and `@prev` to point from a bibl containing a `<note>` in front of "Saturnum" to the first bibl actually containing the citation word "Basilius".
