### ISSUE TITLE
Render editorial markup as in legacy site

### ISSUE THREAD

**Issue by Conal-Tuohy** [IUBLibTech/newton_chymistry#16]
All diplomatic and normalized manuscript styling reflecting editorial interventions needs to be
preserved as seen on the current web site.

See [styling cheatsheet](https://iu.box.com/s/3ji5t91bd8qcbhgo2jqx5fbj2s9zhxjy) for some basic orientation.

**Comment by Conal-Tuohy** [comment]
I have not even made a start on this, but it would be helpful to be able to extract from the legacy rendering stylesheets all the Newton-specific, custom code. To do this it would be necessary I think to find the original version of the TEI stylesheets which this codebase is derived from. By performing a "diff" we can find what has been added. I haven't yet tracked down the source of these stylesheets; if someone can point me to it that would be appreciated.

**Comment by Conal-Tuohy** [comment]
Do we want to base the new display on the current version of the TEI stylesheets? (i.e. a customisation layer on top of the standard stylesheets)

Or should I just write a stylesheet from scratch, to handle all the TEI markup which is _actually used_ in the corpus?

Thoughts?

**Comment by jawalsh** [comment]
I think the Newton stylesheets are based on old Swinburne Project stylesheets that were based on Sebastian Rahtz's TEI P4 stylesheets. I have an old set of the Swinburne stylesheets but I don't know in what state they are or when they were last changed relative to the forking off of the Newton stylesheets. They were abandoned long ago when Swinburne switched to P5.

**Comment by mdalmau** [comment]
https://iu.box.com/s/afeom6msbdnl8pjw7pmmgzv34m755q16

**Comment by Conal-Tuohy** [comment]
This is now done and @wehooper is checking it and raising issues in regard to exceptions. This broadly scoped issue is no longer needed.
