### ISSUE TITLE
Render critical introductions

### ISSUE THREAD

**Issue by Conal-Tuohy** [IUBLibTech/newton_chymistry#17]
Some mss have critical introductions (part of TEI Header). Those need to be provided as a separate display (i.e., link to "critical introduction").
Critical introductions should include links to the normalized and diplomatic views. For example:
see [Dibner MS 1031](http://webapp1.dlib.indiana.edu/newton/mss/intro/ALCH00081/query/field1=text&text1=Dibner%20MS%201031).

**Comment by Conal-Tuohy** [comment]
done

**Comment by Conal-Tuohy** [comment]
How's that?
http://carbon.dlib.indiana.edu:8220/text/ALCH00081/introduction

**Comment by mdalmau** [comment]
Hi.  Final review of mss-related rendition is best served by @wehooper. The footnotes look good, tho.  I did notice that the links to the mss themselves (not sure if they are to the images or to the HTML versions) are not working.

**Comment by Conal-Tuohy** [comment]
Well spotted re the hyperlinks: they are relative URLs pointing to the web pages as generated by XTF. I will need to convert those

**Comment by Conal-Tuohy** [comment]
I notice that in the legacy site, none of the external cross-referencces embedded in the introductions are actually rendered as functional HTML hyperlinks? Is there a reason for that?

**Comment by Conal-Tuohy** [comment]
I think is done now. Anything else/

**Comment by mdalmau** [comment]
Someone like @wehooper or Bill Newman need to sign off on this -- an original project  team member.  I still see one thing with a link that points to a particular page of another mss (6v) -- the anchor isn't working, but I am not sure how critical that is: http://carbon.dlib.indiana.edu:8220/text/ALCH00081/introduction (link [6r-6v] for example).

**Comment by mdalmau** [comment]
@wehooper, we need sign-off on this.  @Conal-Tuohy, any ideas why the anchor isn't working?

**Comment by Conal-Tuohy** [comment]
I just checked and that link appears to be working now (I must've fixed it and forgotten to update this issue).
