### ISSUE TITLE
Display bibliographic citations as popups

### ISSUE THREAD

**Issue by Conal-Tuohy** [IUBLibTech/newton_chymistry#21]
Pop-up/floating boxes denoted by a book icon when ever a citation is encountered in the mss
- Pop-up should stay open, user should close the pop when done
- Show abbreviated citation (title, author, imprint info: date & place of publication)
  - Michelle will provide XPath to these elements once we do some TEI clean-up for the bibliography XML
  - Link title to anchor (#id) in the full bibliography listing

**Comment by Conal-Tuohy** [comment]
Thanks, @mdalmau that's very helpful.

**Comment by Conal-Tuohy** [comment]
I've made the following additions and alterations:

- Added a new pipeline called [`chymistry:download-bibliography`](https://github.com/IUBLibTech/newton_chymistry/commit/68a06093322d297e18c65f199747df9e5fbc7e02#diff-5d0db68a0f2c64b48fd3ee24f1142005), to download the bibliography file from Xubmit. The Administration page has a button which invokes this pipeline by doing a HTTP POST to the URL `/download-bibliography`.
- Added a pipeline called [`chymistry:bibliography-as-html`](https://github.com/IUBLibTech/newton_chymistry/commit/68a06093322d297e18c65f199747df9e5fbc7e02#diff-a1aa6bfe04828c5927108d4fc4f79ce5R247-R258) to display the bibliography as a single HTML page. The pipeline uses a [very simple stylesheet to convert the listBibl into a web page](https://github.com/IUBLibTech/newton_chymistry/commit/68a06093322d297e18c65f199747df9e5fbc7e02#diff-9a86cc36da62c670e7cb8fff29000cfb).
- [Edited the `menus.json` file](https://github.com/IUBLibTech/newton_chymistry/commit/043775d6bcf66dac0039cb35a8541151fb6e666a#diff-efe778ea3ea70d7e050b5540ec447d5b) to add a reference to the bibliography page to the "Online Tools" menu 
 - Modified the existing pipeline for converting an individual MS into HTML, so that it first includes the entire `<listBibl>` from the bibliography into each MS file's `<sourceDesc>`, so that the full details of each citation are available for being rendered into the HTML [Each `<bibl>` in the transcript is then rendered as a hyperlink](https://github.com/IUBLibTech/newton_chymistry/commit/68a06093322d297e18c65f199747df9e5fbc7e02#diff-180d1043fe72b08714dcce6a878b3923), with a popup `title` attribute which is just the plain text of the full citation `<biblStruct>`.

So the plumbing is in place, but there are still questions of how to display an individual citation which are waiting for your input, @ayarnell and @mdalmau

**Comment by Conal-Tuohy** [comment]
I added the book icon

**Comment by Conal-Tuohy** [comment]
What should the popup show?

**Comment by wehooper** [comment]
I've been looking at the bibl popups in Keynes 13 (ALCH00001) and I like them and maybe the others will too. It's great to get the whole entry. Is there formatting in the message, italics, bold?

**Comment by Conal-Tuohy** [comment]
Cheers Wally. The popups are just native browser functionality of displaying an element's `title` attribute. That doesn't allow for formatting. But it would be easy enough to use some Javascript to display a popup div, if it's necessary to go beyond plain text. It seemed to me from looking at the XTF site, that the jquery-based mechanism used there to implement popups would be able to popup snippets of structured HTML, but that it was pretty much only fed plain text, for which HTML's `title` attribute is adequate.

**Comment by Conal-Tuohy** [comment]
@ayarnell it's certainly possible (and super easy) to change the way the citation text is displayed, e.g. displaying only certain elements, displaying labels, and so on. 

But NB if there's a requirement to display more than just plain text (i.e. bold, italics, centering of headings, etc) then I will need to add a feature to format the citation popup as an HTML div, and add Javascript code to pop it up, etc, whereas the mechanism used for the popup at the moment is just the browser's default feature of displaying the content of a `title` attribute.

**Comment by mdalmau** [comment]
Here's information, including XPaths, for the pop-up citations: https://iu.app.box.com/notes/545445019301.  We are working through some of the details with the team, but all agree that it's a good start. Includes instructions for italics, for example.  We will need these to be a Javascript or HTML/CSS pop-up since the box should remain until user either x'es out of box or selects a link.

**Comment by Conal-Tuohy** [comment]
done in https://github.com/IUBLibTech/newton_chymistry/commit/283df7253586ce4826667c45a2d4a302398c17be

**Comment by mdalmau** [comment]
Emailed the Newton team on 8 Dec 2019 for final feedback.  
---------
Hi, all,

Many weeks ago Con completed the integration of the pop-up citations in the Newton mss that Amy has completed thus far (mss before ALCH00032 roughly).  

For example, you can see how the pop-up is working here:
https://newton.dlib.indiana.edu/text/ALCH00001/normalized

Could you please review some examples and send your feedback ASAP (by Weds, 12/11), please?

The main thing I see is more of a design/interface thing and not anything we have funds to fix.  It works. And if this is implemented in a slicker fashion for the Swinburne project, maybe we can use that code.  

Thanks,
Michelle

**Comment by mdalmau** [comment]
Hello Michelle and Con,

The latest version of the citation popups look good.

Removing the onMouseover in favor of a click does prevent the user experiencing unexpected popups when moving the cursor across a page: it's cleaner. 

Then offering links to both the authoritative bibliography entry and any full text reproduction seems useful. Inevitably we found content issues like a missing title that we need to fix, but the machinery certainly seems to be working well.

This looks good too.

Wally and meeting
