### ISSUE TITLE
Install Solr search engine

### ISSUE THREAD

**Issue by Conal-Tuohy** [IUBLibTech/newton_chymistry#25]
Install Solr 7 on the IU server.

Initially, Solr should be installed as a single server (not the cloud configuration) and configured to have a single database ("core") called "index".

I downloaded Solr and followed the steps below, to extract the install script from the tarball, run it, and then create the Solr core.

```bash
tar -xvf solr-7.6.0.tgz 
solr-7.6.0/bin/install_solr_service.sh --strip-components=2
solr-7.6.0/bin/install_solr_service.sh 
tar xzf solr-7.6.0.tgz solr-7.6.0/bin/install_solr_service.sh --strip-components=2
./install_solr_service.sh solr-7.6.0.tgz
cd /opt/solr/
bin/solr create -c index
```

**Comment by randalldfloyd** [comment]
@Conal-Tuohy Thanks! Great to see that we can use Solr 7 and not 8 because we may have that already.  I'm assuming it's easy to adjust the core name on the client side if it needs to be different on the server?

**Comment by Conal-Tuohy** [comment]
Yes it's fine to use a different core name if that's required

**Comment by randalldfloyd** [comment]
@Conal-Tuohy  Solr 7.7.1 Installed and cores created.  I don't want to leave connection details here so I will communicate those via email.

**Comment by Conal-Tuohy** [comment]
Need to update the code so that the Solr connection details are provided as Servlet initialization parameters (specified in the Tomcat context file).

**Comment by Conal-Tuohy** [comment]
Completed in 9a543a9c21bbf9a50b7dfaa77eaa22e4531d15eb
