### ISSUE TITLE
Integrate Latent Semantic Analysis

### ISSUE THREAD

**Issue by Conal-Tuohy** [IUBLibTech/newton_chymistry#28]
The legacy LSA web page is at http://webapp1.dlib.indiana.edu/newton/lsa/index.php

**Comment by Conal-Tuohy** [comment]
Wally says:

> The LSA component runs on Apache not Tomcat, so it hasn’t been an integral part of the Chymistry site, properly speaking. It is an Ajax app written in PHP with links either to a dev mysql database or to a separate, smaller “released” mysql database for the live site. All we really need on the Chymistry sites are the calling links on the respective splash pages. Our sys admins set up the links and redirections to the component and we’ve been using those.

This is actually still slightly unclear to me. I'm assuming that the "splash" page mentioned is the page which contains the Javascript which calls the Ajax app mentioned, and that integrating the LSA component will therefore consist of migrating that HTML page including its `<script>` elements into the new framework by creating a page called `/page/lsa.html`, and also copying the JS libraries it uses into some subfolder of `/static/`.

Is that correct?

**Comment by Conal-Tuohy** [comment]
@wehooper is there anything else that needs doing on this issue?

**Comment by wehooper** [comment]
I tested the link to the LSA component on 8220 and it's working, so the remaining issue is bringing the LSA component's IU branding into compliance. I will get some help from Will who has investigated how to do the rebranding.

**Comment by Conal-Tuohy** [comment]
The XProc pipeline is supposed to be already handling the branding. Is there something specific that's not working you can point me to? If you could give me a link to a page without the correct branding that would be really helpful. Thanks

**Comment by Conal-Tuohy** [comment]
@wehooper if you make some changes to the branding can you keep me in the loop, so I can update the XProc as necessary? Or alternatively, if you remain within the bounds of what the "proxying/rebranding" XProc pipeline is currently expecting (i.e. that [the content to retain is the set of divs in a section with class 'mainContent', plus any scripts](https://github.com/IUBLibTech/newton_chymistry/blob/f6023ed847296fda6a82c648f8606591c5d83016/xslt/rewrite-proxy-response.xsl#L22-L25)), then I can avoid having to do any rework. Cheers!

**Comment by mdalmau** [comment]
@wehooper what's the status on this?

**Comment by mdalmau** [comment]
I still don't have confirmation from @wehooper but am tagging as "future" so we don't lose site of this.
