### ISSUE TITLE
Latent Semantic Analysis (LSA) component

### ISSUE THREAD

**Issue by Conal-Tuohy** [IUBLibTech/newton_chymistry#29]
This existing site's LSA section is a page with an AJAX form, and a set of dynamic result pages backed by a database application.

How should we wrap the existing application in the new site framework?

**Comment by Conal-Tuohy** [comment]
I am keen to rewrite as little as possible that's consistent with integrating these dynamic pages into the new website design, i.e. so that they share the headers and footers of the rest of the site.

An easy way might be to keep this part of the site running unchanged, and proxy to it from the new site (so it would become a back-end web service). The proxy would need to replace the old headers and footers, and rewrite some of the links.

**Comment by wehooper** [comment]
To confirm, let's please leave the LSA component where it is and proxy it as a back-end web service.

I/we have plans for it and want to keep it separate, following the arrangement on the P4 site.

I had been expecting to update the headers and footers when the decisions about those were made, so I will be responsible for bringing the LSA component into visual agreement with the site.

**Comment by Conal-Tuohy** [comment]
I accidentally opened this issue as a duplicate of issue #28
