### ISSUE TITLE
Update Project Team Page

### ISSUE THREAD

**Issue by mdalmau** [IUBLibTech/newton_chymistry#30]
We need to update the staff listing. I would also recommend not embedding our bios in that page but instead linking out to our dept. web pages or own web sites.  The expanding and contracting DIV on that page jumps around too much.

**Comment by Conal-Tuohy** [comment]
That sounds like a good idea to me. I think the expanding/contracting things are not worth it, either. Even if you do retain some minimal bio. The page is just not all that long.

**Comment by mdalmau** [comment]
Leave this open for the Project Team!
