### ISSUE TITLE
sic element / Sept 4

### ISSUE THREAD

**Issue by wehooper** [IUBLibTech/newton_chymistry#31]
The sic elements are currently appending the @corr attribute text to the content and leaving the combined string inline in both diplomatic and normalized. On the old site, the diplomatic version would change the font color of the content to blue, add ‘ \<sic\>’, and set up an on-mouse-over pop-up. The normalized version would just supply the @corr text and carry on.

For testing, there’s an example that’s easy to find right at the top of Keynes 43 (ALCH00032, first document in the current Browse documents listing). ‘Lapie’ should be ‘Lapide’.

**Comment by Conal-Tuohy** [comment]
done in f6023ed847296fda6a82c648f8606591c5d83016

Closing; please reopen if there are problems.
