### ISSUE TITLE
@rend="caret" on add element / sept 4

### ISSUE THREAD

**Issue by wehooper** [IUBLibTech/newton_chymistry#33]
The add elements appear to be functioning correctly, except for the @rend attribute, which encoders used to record when Newton wrote a caret beneath the insertion. Newton's own caret tells us where to insert the text, but he doesn't always give us one.

For example, in the Browser listing, in Keynes 43 (ALCH00032), search for 'cloathed running'. 'cloathed' is in an add element with a @rend="caret" attribute. The word serpent two lines below also has a caret marked, but other add elements in the same paragraph do not.

**Comment by wehooper** [comment]
This issue is still open.

**Comment by Conal-Tuohy** [comment]
Fixed in 40544b4821fdefbac83c9b65138ac098e3cff60e

See http://carbon.dlib.indiana.edu:8220/text/ALCH00032/diplomatic?highlight=man%20cloathed%20running#hit1
