### ISSUE TITLE
old &blankremainder; entity / sept 4

### ISSUE THREAD

**Issue by wehooper** [IUBLibTech/newton_chymistry#35]
The encoders used an entity named &blankremainder; to mark the end pages where Newton left a large part empty.

That entity needs to be replaced, and I think it was used a lot.

For an example, see the bottom of Keynes 43 (ALCH00032).

**Comment by Conal-Tuohy** [comment]
I have all the external entities committed to this git repo in the `p4` folder so it's just a matter of redefining the entity there, see https://github.com/IUBLibTech/newton_chymistry/search?utf8=%E2%9C%93&q=blankremainder&type=

**Comment by Conal-Tuohy** [comment]
What does the entity need to be replaced with? Is that a decision that someone at IU needs to make?

**Comment by wehooper** [comment]
I will raise this question at the weekly meeting, Fri 13 Sept.

**Comment by wehooper** [comment]
Hi Con, I checked the entity definition for blankremainder at the link above, and that definition looks correct. The desired text is appearing in italic and angle brackets as it should. Another one down.
