### ISSUE TITLE
seg type = "hand"

### ISSUE THREAD

**Issue by wehooper** [IUBLibTech/newton_chymistry#37]
We have seg elements with type="hand" and corresp=writer attributes. In both normalized and diplomatic versions, we color the content of the seg blue and set up a popup-on-mouseover that either displays the corresp value directly, or uses the corresp value to retrieve information from physDesc/handDesc/handNote in the document's TEI header.

An example where the P4 code displays the corresp value directly is in Keynes 12, ALCH00001.xml, the very first number after the page break, 16, but that document has no handDesc. http://carbon.dlib.indiana.edu:8215/newton-dev/mss/norm/ALCH00001/

An example where it uses the corresp value to pull the popup message from handDesc can be found at the top of Keynes 15, ALCH00004, the numbers '5/6/7' pulling "Unknown hand" and the number 27 on the next line pulling "Unknown hand 2." http://carbon.dlib.indiana.edu:8215/newton-dev/mss/dipl/ALCH00004/

**Comment by wehooper** [comment]
<seg type="hand"> still an open issue. Oct 2 Wed.

**Comment by Conal-Tuohy** [comment]
This looks like something that should really have been encoded using the TEI [`<hand>` element and associated `@hand` attribute](https://tei-c.org/Vault/P4/doc/html/PH.html#PHDH). 

Is that right? Or is there some reason for using this different convention?

If it is in fact OK to use the standard mechanism, I think it'd be best to re-encode it that way as part of the P5 conversion.

The current TEI looks like this:
```xml
<!-- convention used in P4 -->
<seg type="hand" corresp="unknown">16</seg>
```
It would convert to the following P5:
```xml
<!-- P5 -->
<!-- in the header -->
<handDesc>
<handNote xml:id="hand-unknown">unknown</handNote>
</handDesc>
...
<!-- in the text -->
<seg hand="#hand-unknown">16</seg>
```
The P5 would then be converted to the following HTML:
```html
<seg title="unknown" class="tei-seg type-hand">16</seg>
```

**Comment by wehooper** [comment]
We want to follow the scheme you describe.

Can our P4 conventions can be converted the new P5 forms programmatically, or will some parts need handwork?

**Comment by Conal-Tuohy** [comment]
I have converted `<seg type="hand" corresp="foo">` to `<seg hand="#foo">` in the P4-to-P5 conversion pipeline. In the HTML rendering, the corresponding element gets a `title` attribute (producing a popup) which is populated from the value of the `scribe` attribute of the linked `handDesc` element.

I think that's it; I don't think there's any "handwork" needed.

**Comment by wehooper** [comment]
It looks like the element is working correctly. So this is a signoff.
