### ISSUE TITLE
paragraph element p not indenting

### ISSUE THREAD

**Issue by wehooper** [IUBLibTech/newton_chymistry#39]
For example, in Keynes 12, ALCH00001.xml, after the numbered items at the top of the document, Newton begins a sequence of indented paragraphs (at line 498 in the xml) that we've encoded with \<p\> elements. Search for 'Educ salem e metallis: qui'. They should indent.

8220: http://carbon.dlib.indiana.edu:8220/text/ALCH00001/diplomatic#?c=&m=&s=&cv=&xywh=-1%2C-1%2C1%2C1
8215: http://carbon.dlib.indiana.edu:8215/newton-dev/mss/norm/ALCH00001/

**Comment by wehooper** [comment]
This issue is still open.

**Comment by wehooper** [comment]
In Portsmouth 3973/ALCH00109, the <p> appears to add points/space between the paragraphs.

P4:  [http://carbon.dlib.indiana.edu:8215/newton-dev/mss/dipl/ALCH00109/](url), top of the file.
P5:  [http://carbon.dlib.indiana.edu:8220/text/ALCH00109/normalized#?c=&m=&s=&cv=](url).

**Comment by Conal-Tuohy** [comment]
addressed in 68eaeba3affbefd406c29b8b8f952ffe23aba113
