### ISSUE TITLE
hi rend="u" for underlining not working

### ISSUE THREAD

**Issue by wehooper** [IUBLibTech/newton_chymistry#40]
There's an example of Newton's underlining (also) in Keynes 12, ALCH00001.xml, near the bottom of the first folio, where he underlined 'aqua' in the sentence beginning "Haec aqua multiplicari potest . . ."

http://carbon.dlib.indiana.edu:8220/text/ALCH00001/diplomatic#?c=&m=&s=&cv=&xywh=-1%2C-1%2C1%2C1
http://carbon.dlib.indiana.edu:8215/newton-dev/mss/dipl/ALCH00001/f1r

**Comment by wehooper** [comment]
Issue still open, wed 2 oct

**Comment by wehooper** [comment]
hi rend="super" also not working, for an example of that compare the dated paragraphs that begin Portsmouth 3973/ALCH00109, which have several instances. Some of those use entities, like \&the; which have hi rend="super" defined into them. Compare:
P4: [http://carbon.dlib.indiana.edu:8215/newton-dev/mss/dipl/ALCH00109/](url)
P5: [http://carbon.dlib.indiana.edu:8220/text/ALCH00109/diplomatic#?c=&m=&s=&cv=](url)

**Comment by Conal-Tuohy** [comment]
fixed in 68eaeba3affbefd406c29b8b8f952ffe23aba113
