### ISSUE TITLE
<fw> place attribute not rendering

### ISSUE THREAD

**Issue by wehooper** [IUBLibTech/newton_chymistry#41]
The encoders used the place attribute on fw to mark the position, but the place attribute is not being used in rendering.

There's a good example at the top of ALCH00109, Experiments, Portsmouth 3973, where fw was used to encode fresh librarian's markings not found on our original microfilms. The scraps of text "1 ADD 3973" and "1a" are the things to compare: [http://carbon.dlib.indiana.edu:8220/text/ALCH00109/diplomatic#?c=&m=&s=&cv=](url).

P4 example:  [http://carbon.dlib.indiana.edu:8215/newton-dev/mss/norm/ALCH00109](url)

**Comment by Conal-Tuohy** [comment]
addressed in 68eaeba3affbefd406c29b8b8f952ffe23aba113
