### ISSUE TITLE
<del rend=strike> containing <space>

### ISSUE THREAD

**Issue by wehooper** [IUBLibTech/newton_chymistry#43]
At line 483 of ALCH00109.xml, Portsmouth 3973, "Experiments," we have a \<del\> containing a <space dim="horizontal" extent="25"\>. We use this strategy to capture lines or rules that Newton draws. 

Search for "brittle like a cindre" in Portsmouth 3973 in a browser. The rule should fall at the end of that line. That's midway down f.1v.

**Comment by wehooper** [comment]
There is an instance of \<del rend="overdash"\> near the top of ALCH00081.xml, Dibner 1031 B, "Of Natures obvious laws . . . ," which produces a dashed overline.

See ALCH00081.xml line 406.

In browsers, P4: [http://webapp1.dlib.indiana.edu/newton/mss/dipl/ALCH00081/](url), search "may be" from top.
P5: [http://carbon.dlib.indiana.edu:8220/text/ALCH00081/diplomatic#?c=&m=&s=&cv=0&xywh=-1%2C0%2C1%2C1](url)

**Comment by wehooper** [comment]
There's another case in 1031 B where "overdash" is used inside \<add\>. Search for 'indurated'. We used the overdash when Newton struck a word in a sentence, and then a later time drew a line through the whole sentence. We decided to use marks above x-height since overstrikes-on-overstrikes look like overstrikes (occurring half-x-height). The overstriking of the word 'indurated' is visible because it appears in the \<add\>. Can you see another solution to this general problem apart from using an overdash versus overstrike? More tools may be available now.

**Comment by wehooper** [comment]
I just found a \<del rend="none"\> in 1031 B. Search for 'standing water'. That phrase occurs in an \<add\> and in the page image you can see Newton has written a lower-case 'w' but it's not struck out. Judging by the P4 output, we supported that case and no overstrike was applied. I expect I was involved but I don't remember this. Jim encoded it, I could raise with the gang if you like.

**Comment by Conal-Tuohy** [comment]
@wehooper can you clarify these last two points, please? With links? They sound unrelated to the issue, to me.

**Comment by Conal-Tuohy** [comment]
Re-reading the comment about `del[@rend='none']` and I find that it makes more sense to me now. Though it's not really a "deletion" is it, if it's left unmarked? I would have thought it should be a `<surplus>`. I'd suggest fixing it by transforming the P4 `del[@rend='none']` into a P5 `surplus`.

> [del](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-del.html) indicates a deletion present in the source being transcribed, which states the author's or a later scribe's intent to cancel or remove text. [surplus](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-surplus.html) indicates material present in the source being transcribed which should have been so deleted, but which is not in fact.
https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-del.html

**Comment by wehooper** [comment]
Hey, thanks for the information about \<surplus\>. I'd say you're right by that reading. I will definitely pass this on the group.

**Comment by wehooper** [comment]
We discussed the use of \<surplus\> instead of \<del rend="none"\>, and agree that using surplus is more appropriate. The guidelines suggest surplus should be used for unnecessary repetitions, like "the the," and we have been using sic for those cases, and there are many of those, and they may be difficult to distinguish among all the sic's by machine.

For that reason, we want to restrict the use of the surplus element to del with rend="none", but we agree with making that change.

**Comment by Conal-Tuohy** [comment]
@wehooper I'm still not sure I got the gist of this comment:

> There's another case in 1031 B where "overdash" is used inside <add>. Search for 'indurated'. We used the overdash when Newton struck a word in a sentence, and then a later time drew a line through the whole sentence. We decided to use marks above x-height since overstrikes-on-overstrikes look like overstrikes (occurring half-x-height). The overstriking of the word 'indurated' is visible because it appears in the <add>. Can you see another solution to this general problem apart from using an overdash versus overstrike? More tools may be available now.

.. but I have it looking like it does in the legacy site. Is that enough?

**Comment by Conal-Tuohy** [comment]
I think this issue is all done. @wehooper can you confirm, and close it if so?

**Comment by wehooper** [comment]
The overdashes are fine. This is done, thanks!
