### ISSUE TITLE
<unclear> with no attributes

### ISSUE THREAD

**Issue by wehooper** [IUBLibTech/newton_chymistry#49]
In most cases the encoders provided both reason and resp attributes, but in 55 cases the unclear elements have no attributes at all. They mostly occur in the earliest documents our team transcribed.

Our P4 xslt template for "unclear" does nothing to or with the content of the unclear element if there is no reason attribute, so nothing appears and our review did not catch the missing cases.

It is our encoding mistake, but can it be fixed in the transform by adding a generic reason, like reason="under review" that would stand out in an Oxygen search, but hopefully wouldn't cause a reader to pause much? Bill was at a conference and we couldn't decide on what value to use. Is there something appropriate?

**Comment by Conal-Tuohy** [comment]
I think you can search in Oxygen by XPath, can't you? That's what I'd recommend. e.g.

```xpath
//tei:unclear[not(@reason)]
```

**Comment by Conal-Tuohy** [comment]
Or text search for `<unclear>`?

**Comment by wehooper** [comment]
Okay, we'll take responsibility for this problem. I'll close this version of the issue and open it again flagging Michelle and others, without assigning it to you.
