### ISSUE TITLE
nb.xml

### ISSUE THREAD

**Issue by Conal-Tuohy** [IUBLibTech/newton_chymistry#52]
The `<bibl>` elements are marked as corresponding to elements in a file called `nb.xml`, but there doesn't appear to be any such file. The HTML conversion assumes that this actually refers to the file `CHYM000001.xml`

e.g. from ALCH00117.xml

```xml
<bibl corresp="nb.xml#Zetzner1661"><abbr>Elucid</abbr> p. 236. </bibl> 
```

**Comment by Conal-Tuohy** [comment]
This is mostly just a note for future reference.

**Comment by mdalmau** [comment]
Thank you.  We can automate that check  after the students are done encoding the bibls

**Comment by Conal-Tuohy** [comment]
Yeah I think a global replace of `nb.xml#` with `CHYM000001.xml#` will sort it, but the pipeline is actually ignoring the part of the URL before the `#` anyway, so it will make no practical difference; it's just an inconsistency I noted.

**Comment by mdalmau** [comment]
Let's leave this issue open for the Team!  Thanks, Con.
