### ISSUE TITLE
Display images from new IIIF image server

### ISSUE THREAD

**Issue by Conal-Tuohy** [IUBLibTech/newton_chymistry#53]
We need to plug the new image server into the application; by supplying manifests to UniversalViewer which invoke the image server to render manuscript images.

**Comment by Conal-Tuohy** [comment]
We have [one Pages-generated IIIF manifest](http://webapp-devel.dlib.indiana.edu/pages_devel/concern/scanned_resources/tdf65v796w/manifest), for the manuscript ALCH00002

**Comment by Conal-Tuohy** [comment]
All the TEI documents need to be updated to include their IIIF manifest URI. The pipeline is looking for this in the form an `<idno>` element within the Manuscript Description section of the TEI file. Here's an example of the relevant section from `ALCH00002` which the manifest URI at the end of the `msIdentifier`, encoded as an `altIdentifier` containing an `idno` whose type is `iiif-manifest`.

```xml
<msIdentifier>
    <country key="gb-en">United Kingdom</country>
    <region key="en" type="state">England</region>
    <settlement>Cambridge</settlement>
    <institution>Cambridge University</institution>
    <repository>King's College Library</repository>
    <collection>Keynes</collection>
    <idno>MS. 13</idno>
    <altIdentifier>
        <idno type="collection">Keynes</idno>
    </altIdentifier>
    <altIdentifier>
        <idno type="sotheby_lot">SL2</idno>
    </altIdentifier>
    <altIdentifier>
        <settlement>Bloomington</settlement>
        <institution>Indiana University</institution>
        <repository>Digital Library Program</repository>
        <idno type="iunp">ALCH00002</idno>
    </altIdentifier>    
    <altIdentifier>
        <idno type="iiif-manifest">http://webapp-devel.dlib.indiana.edu/pages_devel/concern/scanned_resources/tdf65v796w/manifest</idno>
    </altIdentifier>
</msIdentifier>
```

**Comment by mdalmau** [comment]
I will need @randalldfloyd's help with the CORS header comment above!

**Comment by mdalmau** [comment]
Per @Conal-Tuohy's request, I added another ```<idno>``` to the header for ALCH0002 to provide an explicit link to the iiif manifest.  The TEI was modified to ensure validity:
```
<altIdentifier>
                            <settlement>Bloomington</settlement>
                             <institution>Indiana University</institution>
                             <repository>Indiana University Libraries</repository>
                             <idno type="iiif-manifest">http://webapp-devel.dlib.indiana.edu/pages_devel/concern/scanned_resources/tdf65v796w/manifest</idno>
                         </altIdentifier>
```
The file has been updated via Xubmit and can be testing.  

ONE BIG CAVEAT:  We need to use the production URL, not the dev URL moving forward.  I will need to talk to Nick Homenda about this.

**Comment by mdalmau** [comment]
@Conal-Tuohy and @randalldfloyd I think we need to talk about this some more in person.  In talking to our Head of Repo Services, it appears that the CORS header fix is not so easy (no sure why -- maybe it'll break other things).  I will find Randall in  the  next couple of days to iron things out.

**Comment by Conal-Tuohy** [comment]
I hope they manage to sort out the problem (I'm assuming it's just a technical problem) because an IIIF server really does need CORS. If it remains a hold-up, though, we can work around it.

**Comment by randalldfloyd** [comment]
@Conal-Tuohy Can you give me some additional context as to when the CORS exception occurs?  Is this occurring when the UV is embedded in the app hosted on our dev server, or when accessing via a dev environment of yours? Can you give me an example URL of an item with working TEI/manifest that produces a CORS error?

**Comment by Conal-Tuohy** [comment]
@randalldfloyd 

NB The problem actually occurs in the user's browser, so it makes no difference what host the XProc server is running on; the problem arises from the fact that the XProc application server which hosts the page in which UV is embedded (whether dlib.indiana.edu or my own local VM "alchemy") is not the same server as the one from which UV attempts to load the manifest (either webapp-devel.dlib.indiana.edu or pages.dlib.indiana.edu).

Currently we have only one TEI P4 file in Xubmit which contains a reference to a manifest, and it's the non-production URL: http://webapp-devel.dlib.indiana.edu/pages_devel/concern/scanned_resources/tdf65v796w/manifest, so, although I know Michelle is going to update that URL soon, just to cut to the chase, I have just now manually edited the P5 file on carbon which has been derived from that file, replacing that URL with https://pages.dlib.indiana.edu/concern/scanned_resources/dc821gv53p/manifest, so that you can view the problem, with the production manifest URL, in the page at
http://carbon.dlib.indiana.edu:8220/text/ALCH00002/diplomatic

The Universal Viewer widget is instantiated in that page as soon as the page loads (it's just hidden by CSS rules), so UV immediately attempts to dereference the manifest URL, which produces a CORS error. Running Firefox I can see this error message appear in the browser's console:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pages.dlib.indiana.edu/concern/scanned_resources/dc821gv53p/manifest. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

From Firefox's network log panel, it looks like Firefox has made a GET request for that URL, and received the actual manifest, with an HTTP 200 OK result, and the JSON content is all fine and dandy. What's missing from the response is only an `Access-Control-Allow-Origin` header, which should have the value `*` in order to make the manifest usable by any host; without it, the manifest can only be legally used in a web page which itself loaded from the pages.dlib.indiana.edu host, and so Firefox throws an exception and UV then does not get to see the manifest (even though it has been downloaded).

A quick way to check your CORS setup is using a command-line tool like curl, e.g. 

```bash
curl -I https://pages.dlib.indiana.edu/concern/scanned_resources/dc821gv53p/manifest
HTTP/1.1 200 OK
Date: Wed, 06 Nov 2019 02:49:35 GMT
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Vary: Accept
Content-Type: application/json; charset=utf-8
ETag: W/"07fa4d1a047fc0e88ce2e5c9b0416738"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 7b7fbdf4-d628-49f5-b2aa-f08f62d0fd88
X-Runtime: 0.014377
Strict-Transport-Security: max-age=31536000
```

A working example (taken from the UniversalViewer website) is:

```bash
curl -I https://d.lib.ncsu.edu/collections/catalog/nubian-message-1992-11-30/manifest
HTTP/1.1 200 OK
Date: Wed, 06 Nov 2019 03:01:20 GMT
Server: Apache
Cache-Control: max-age=0, private, must-revalidate
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000
X-XSS-Protection: 1; mode=block
X-Request-Id: 67e43f81-787b-4a85-9f95-1f9c8e96dc49
Access-Control-Allow-Headers: *
Access-Control-Allow-Methods: POST, GET, OPTIONS
X-Frame-Options: SAMEORIGIN
X-Runtime: 0.083422
X-Content-Type-Options: nosniff
X-Powered-By: Phusion Passenger 6.0.2
Transfer-Encoding: chunked
ETag: W/"6ccbabf7e03a7163c16da67ffa9dad4a"
Status: 200 OK
Content-Type: application/json; charset=utf-8
```

**Comment by Conal-Tuohy** [comment]
This may be useful https://enable-cors.org/

**Comment by randalldfloyd** [comment]
@Conal-Tuohy Thanks for all that.  I know a bit about CORS but I still couldn't quite get in my head from the original discussion whether it was the Xproc application host that needed CORS enabled or the Pages (IIIF manifest) host.  That helps clear that up. There is no technical issue, that got kind of mixed up in the translation, but I will have to beg a bit of buy-in from our sysadmin.  As to that, it will sit easier with him if we enable CORS but wildcard it to IU domains initially.  That means it would work as deployed on our server but your own dev environment wouldn't work, so you would have to mock your own manifest or connect via VPN.

**Comment by Conal-Tuohy** [comment]
@randalldfloyd I'm pretty sure that a wild-card is in fact not possible with CORS; I think you either have `*` or an exhaustive list of host specifications which are interpreted strictly literally, including protocol, hostname, and port number. I believe that in practice the only workable value for an IIIF server to offer is `*`.

**Comment by Conal-Tuohy** [comment]
If you think this is wrong, and still want to try a wildcard solution (which I very much recommend against), can you please ensure the result is workable, by checking it with this service? http://universalviewer.io/#view

**Comment by mdalmau** [comment]
@randalldfloyd configured a PURL that points to the manifest for each mss so we will need to update the TEI P5 with this information.  For now, I am documenting here, what the PURL looks like and a caveat about working links in Pages (at the moment).  I will meet with Randall on 9 Dec 2019  to discuss this further:

---------
I got PURLs all setup and tested for Newton!  The only wrinkle, which isn't a problem just yet, is that my changes to Pages to resolve the Newton ID to the internal ID/manifest hasn't been merged or deployed to production Pages.  It has been deployed to the dev/stage version, so currently the PURLs redirect there instead.  That just means that any items you want to test with need to be uploaded there ( http://webapp-devel.dlib.indiana.edu/pages_devel/ ).

However the PURL pattern that you need for encoding into the TEI won't change, which is:

**https://purl.dlib.indiana.edu/iudl/newton/iiif/(itemID)** 

Once production Pages has been updated I just have to make a simple one-liner change to redirect there.  Note that webapp-devel isn't currently SSL enabled so everything I just described may actually break for you per this past week's discussion on forced SSL in the browser.  We didn't know that had never been done for that host so Brian is awaiting a cert for it.

**Comment by Conal-Tuohy** [comment]
@mdalmau or @randalldfloyd can you please confirm the PURL? 

I'm a bit confused by the message above; I'm not sure whether I should expect PURLs matching this pattern should currently resolve to a "production" manifest, or to a "test" manifest, or whether I should expect them to be broken? Because they do seem currently broken; perhaps I've misinterpreted the pattern, but this URL gives me an error: https://purl.dlib.indiana.edu/iudl/newton/iiif/ALCH00002 

Can you please provide a working example URL? 

It will be very easy to insert these manifest URIs into the P4-to-P5 conversion step, once the PURL resolver is configured, and I know what the URIs should actually look like.

**Comment by mdalmau** [comment]
The PURL current point to dev pages which only have 2 of Newton mss. Try inserting the purl for these two mss:     * ALCH00002  ***
    * ALCH00095 ***

@randalldfloyd will coordinate with the pages web dev team to update the purl resolver to point to production by next week, the latest. If the purl works for the 2 above (it does when resolving the PURL directly) then it *should* work for the others once the PURL resolver is updated.

**Comment by Conal-Tuohy** [comment]
https://purl.dlib.indiana.edu/iudl/newton/iiif/ALCH00002 was the one I'd tried (it's broken). But I see that https://purl.dlib.indiana.edu/iudl/newton/iiif/ALCH00095 works. Thanks!

**Comment by randalldfloyd** [comment]
@Conal-Tuohy , @mdalmau The first one (ALCH00002) should have worked, that's probably just a minor bug in the regex not matching the identifier.  I'll look into that but at least we have one (ALCH00095) that works so that we can see it working end-to-end.

**Comment by randalldfloyd** [comment]
@Conal-Tuohy , @mdalmau ALCH00002 works now as well. The identifier field used to perform the resolution lookup wasn't set for that item.  So it isn't a code problem as much as a record issue, and I'm not sure when and where that should have been set, and by what.  I'll have to inspect the items in the production instance to see if that's true for those.

**Comment by randalldfloyd** [comment]
@Conal-Tuohy @mdalmau 
I made sure all of the objects in the production instance have the correct identifier field used to resolve the Newton ID to the internal ID during PURL resolution.  At this point we should be confident enough in the interaction end-to-end to encode that PURL pattern into all documents.  On Friday I am planning to deploy the latest code to production Pages, which is currently missing the latest commits to support Newton PURL resolution. At that point I will simply switch the PURL server's redirect location and all documents should work correctly.

**Comment by mdalmau** [comment]
We know this works, but haven't been able to update the TEI Headers to point to the IIIF manifest PURLs for all the mss that are currently publicly available.  This is also hinges to some degree on issue #55 and issue #54.

**Comment by mdalmau** [comment]
@randalldfloyd the TEI headers contain the PURLs to the IIIF manifest but the page images aren't loading.  I thought I'd start with you to see if that's a PURL config issue (or an application issue in which case we need @Conal-Tuohy's help).
