### ISSUE TITLE
fix cases of <unclear> with attributes

### ISSUE THREAD

**Issue by wehooper** [IUBLibTech/newton_chymistry#56]
We have discussed this in a meeting in October, and Con prefers that we fix the problem. It probably should be done by us. I'm using github to transition this issue to newton home team responsibility, and haven't assigned Con.

Here's what I wrote in the original issue:

In most cases of <unclear> the encoders provided both reason and resp attributes, but in 55 cases the unclear elements have no attributes at all. They mostly occur in the earliest documents our team transcribed.

Our P4 xslt template for "unclear" does nothing to or with the content of the unclear element if there is no reason attribute, so nothing appears and, I think, for that reason our review did not catch the missing cases.

It is our encoding mistake, but can it be fixed in the transform by adding a generic reason, like reason="under review" that would stand out in an Oxygen search, but hopefully wouldn't cause a reader to pause much? Is there something appropriate?

**Comment by wehooper** [comment]
Wally will run the P5 batch job on the problem files to update the unclear elements that have this problem and then close this issue.

**Comment by mdalmau** [comment]
As I understand this issue, we need to update some encoding.  A re-index once complete should solve the problem and the reason for unclear should show up.  Tabling this for future fix.
