### ISSUE TITLE
handNote/@scribe attribute not valid in the P5

### ISSUE THREAD

**Issue by mdalmau** [IUBLibTech/newton_chymistry#58]
In testing the Xubmit repo for the P5 files, we discovered a p4=>p5 bit of encoding that was not valid in the Header: handNote/@scribe. @Conal-Tuohy stated in an email that he'd fix this in his convert XSLT.

**Comment by Conal-Tuohy** [comment]
fixed in 8d7346f723daa73ae2167ffd9722b75a0596226c
