### ISSUE TITLE
Prod Site needs to point to SOLR chym_prod Core

### ISSUE THREAD

**Issue by mdalmau** [IUBLibTech/newton_chymistry#65]
SOLR cores: chym_dev, chym_prod
When site is ready for production,  we need to point to SOLR core: chym_prod. 

- Need to remember that the chym_dev core will index ALL manuscripts despite their Xubmit statuses and chym_prod will only index published mss. See also #59

**Comment by randalldfloyd** [comment]
> SOLR cores: chym_dev, chym_prod
> When site is ready for production, we need to point to SOLR core: chym_prod.
> 
>     * Need to remember that the chym_dev core will index ALL manuscripts despite their Xubmit statuses and chym_prod will only index published mss. See also #59

@mdalmau I have a new Solr production core populated but then I found this comment.  I didn't see where I was supposed to somehow constrain manuscripts from Xubmit by status.  Do you know what should control that?  A setting somewhere?

**Comment by mdalmau** [comment]
From my notes for when we did the walkthrough with Con (but we have also discussed this over email, which I am trying to dig up now):  dc:coverage field in Xubmit (the value, I am assuming for this field should be either "production" or "development."  I am assuming that the "publication status" field that the user sees in Newton Xubmit is mapped to dc:coverage.

**Comment by mdalmau** [comment]
<dc:coverage>Production</dc:coverage>
<dc:coverage>Development</dc:coverage>

**Comment by randalldfloyd** [comment]
Confirmed done 2021-01-28
