### ISSUE TITLE
<item> elements in <list rend='inline'> rendered with line breaks instead of collapsing

### ISSUE THREAD

**Issue by wehooper** [IUBLibTech/newton_chymistry#66]
In Babson 421, at the top of folio 4r, line 607 in ALCH00095.xml, Newton wrote a list of head words, author's names mainly, in a common paragraph format. We decided to encode that text with a <list> element and parse the authors and other head words with <item> elements.

http://carbon.dlib.indiana.edu:8220/text/ALCH00095/diplomatic

We added a rend attribute to signal these cases, <list rend="inline">, and we suppressed the line breaks to create the inline list.

**Comment by mdalmau** [comment]
Closing issues so that we can better track production deployment.  Issues with the tag "future" need to be addressed at some point.
