### ISSUE TITLE
<del> On mouse-over of a strikeout, msg is 'Hand: ' for @hand="in"

### ISSUE THREAD

**Issue by wehooper** [IUBLibTech/newton_chymistry#67]
When the user mouses over any strikeout, the popup message shows 'Hand: '. Check the top of Babson 421, http://carbon.dlib.indiana.edu:8220/text/ALCH00095/diplomatic, and search 'tinctura' for the rendering.

In Oxygen, ALCH00095.xml at line 391, there is a \<del\> with the attribute hand="in". Above that, at line 247, I found a \<handNote\> element that may be related. It contains an empty paragraph element.

Is that an issue in the XSLT, or in our TEI?

I checked the P4 rendering of strikeouts and it looks like we didn't do a popup. This may be easy.

I haven't thought this one through. Is there a design goal? Show that I.N. made the strikeout? (I would be more inclined to to report the hand only if we know it wasn't Newton who made the strike, but that's just my two cents.)

**Comment by Conal-Tuohy** [comment]
In the XSLT we have:
```xslt
<xsl:if test="@hand">
	<xsl:variable name="hand" select="key('hand-note-by-reference', @hand)"/>
	<xsl:attribute name="title" select="concat('Hand: ', $hand/@scribe)"/>
</xsl:if>
```
i.e. if the `@hand` attribute exists it's used to look up a `<handNote>` by id, and the value of the resulting `handNote` is prefixed with "Hand: " to use as a popup message. Here the `handNote` is empty; maybe the solution is just to ignore such missing `handNote` elements?

**Comment by mdalmau** [comment]
Closing issues so that we can better track production deployment.  Issues with the tag "future" need to be addressed at some point.
