### ISSUE TITLE
Location of switch between diplomatic and normalized renderings of a document?

### ISSUE THREAD

**Issue by wehooper** [IUBLibTech/newton_chymistry#70]
I don't know how to switch between diplomatic and normalized renderings of the documents. In the P4 renderings we could click on the folio milestone, e.g. \<2r\>, to change views.

Currently to proof read the P5 normalized version I am modifying the URL by hand and keeping the normalized open on its own tab.

I bet someone told me how to do this and I've forgotten.

**Comment by mdalmau** [comment]
I never noticed  this not working  because I never tried!  I usually toggle at the top-level but  I  don't use  the site like Wally or Bill would.   The page numbers on the new site look like the same link  color as the old site, but they aren't links. Maybe it's an easy fix, @Conal-Tuohy?

**Comment by Conal-Tuohy** [comment]
I was not aware that the page numbers in the old system were links to the _other_ view of the current page. I missed that. A very easy fix to make, though, yes.

**Comment by mdalmau** [comment]
@Conal-Tuohy emailed Con on 6/3/2020 about estimating costs for fixing this issue.

**Comment by mdalmau** [comment]
@Conal-Tuohy thank you for addressing this issue.  From Conal:
I've committed the change to github but I haven't deployed it anywhere beyond my local dev VM. It just needs a "git pull" and it's done. 
------
Is the "git pull" needed to update Carbon?  This is where I am reluctant to do anything in Git until I understand how it all works. @randalldfloyd any idea?

**Comment by Conal-Tuohy** [comment]
Yes that's right; you need to run `git pull` on the server(s) where the XProc code is installed.

**Comment by mdalmau** [comment]
@randalldfloyd, could you do this when you get a chance so we can test?  Once we test, I can close this issue!  Thanks.

**Comment by mdalmau** [comment]
It is working!
