### ISSUE TITLE
Project Team Page Needs Updating

### ISSUE THREAD

**Issue by mdalmau** [IUBLibTech/newton_chymistry#83]
Project Team page, Michelle only has LOREM IPSUM under her name! Everyone should probably check to see if their bios are up to date. Also, should the project team page be updated to show me, Takatomo, Justina, and anyone else who has participated since that page was last updated. Reported by Alex Wingate.

**Comment by mdalmau** [comment]
I will come up with a list of updates for that Project Team page and post here for @tubesoft to add to his to-do list.

**Comment by Conal-Tuohy** [comment]
could I get a name-check on that page, too, please?

**Comment by mdalmau** [comment]
Absolutely @Conal-Tuohy! Could you post here how we should credit you (by name, by company name, both, etc.).

**Comment by Conal-Tuohy** [comment]
Thanks! Maybe something like this?

Conal Tuohy, Developer and TEI Consultant, http://conaltuohy.com/

**Comment by mdalmau** [comment]
@tubesoft this needs to be finalized still, but the content updates from this page will be posted here: https://docs.google.com/document/d/1bUGG_Re_EQUptJUeOLFno99N3JE3mNA-3MqZosRzZqY/edit#

**Comment by mdalmau** [comment]
Updated but still have pending questions: https://docs.google.com/document/d/1bUGG_Re_EQUptJUeOLFno99N3JE3mNA-3MqZosRzZqY/edit#heading=h.rf55n02is43y (will cover at meeting today, April 27, 2021)

**Comment by wehooper** [comment]
June 3, '21.  The current state of the Project Team page is as agreed by the team at the last meeting discussion we had (May).
We expect future changes!  :)
