### ISSUE TITLE
Alchemical Glossary does not have A-Z navigation.

### ISSUE THREAD

**Issue by mdalmau** [IUBLibTech/newton_chymistry#84]
The Alchemical Glossary doesn’t have an alphabet for navigation both in Possum and Carbon while the current live site does. Reported by Alex Wingate.

**Comment by mdalmau** [comment]
My guess is this is something we missed and won't fix but will verify.

**Comment by tubesoft** [comment]
As far as I briefly investigated, on the P4 site, A-Z navigation uses some jQuery plugin. I don't think the P5 site no longer uses jQuery, so it is not possible to replicate in a P4 site way.
We could implement a similar feature only with CSS like [this website](https://www.smileycat.com/how-to-style-an-a-to-z-index-with-css/). If we need, I can try it.

**Comment by tubesoft** [comment]
Added at #104

**Comment by wehooper** [comment]
This problem was fixed elegantly. Let's close this.
