### ISSUE TITLE
Update Articles & Presentation Page 

### ISSUE THREAD

**Issue by mdalmau** [IUBLibTech/newton_chymistry#86]
Does the academic article section in Articles & Presentations need to be updated with your latest article that you all wrote? Reported by Alex Wingate.

**Comment by mdalmau** [comment]
I will come up with a list of updates for that Articles & Presentation page and post here for @tubesoft  to add to his to-do list.

**Comment by mdalmau** [comment]
I started a document to share with Project team for updating: https://docs.google.com/document/d/1Hwy6j_W0ktaUKW8Rjbzl7_pYIOFuqxcKxvcBEo36vYk/edit#

**Comment by wehooper** [comment]
To the best of my knowledge, the Papers and Presentations webpage is up to date and we can close this particular issue.
