### ISSUE TITLE
Include HTML pages in search index

### ISSUE THREAD

**Issue by Conal-Tuohy** [IUBLibTech/newton_chymistry#9]
Search should index all TEI content. If time permits, the search index should also include selected HTML pages.

- Set up an HTML configuration index file or document a way for us to alter that HTML
index.

- For starters, index the following pages:

  - critical introductions
  - Educational Resources => Chymical Products, Experiments in Mineral Acids and Multimedia Lab

Need to plan for differentiating the results from encoded manuscripts and html pages

**Comment by mdalmau** [comment]
We don't need to index the HTML pages along with the TEI.  We can close this issue.
