### ISSUE TITLE
Manuscript title on the transcription page?

### ISSUE THREAD

**Issue by tubesoft** [IUBLibTech/newton_chymistry#91]
On P4 site, for example [Keynes 12](http://webapp1.dlib.indiana.edu/newton/mss/dipl/ALCH00001/), the title of the manuscript, "Keynes MS. 12, King's College Library, Cambridge University" appears on the top of the page. However, on [P5 site](http://carbon.dlib.indiana.edu:8220/text/ALCH00001/diplomatic#?c=&m=&s=&cv=&xywh=-701%2C0%2C2815%2C1830), there is nothing like that on the transcription page, which seem inconvenient. In the he previous weekly meeting, we agreed that we should add the title.

**Comment by mdalmau** [comment]
We would like the title to reflect the TEI elements concatenated on the P4 site: http://webapp1.dlib.indiana.edu/newton/mss/norm/ALCH00001/.

**Comment by tubesoft** [comment]
I modified the rendition like this:
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/17519127/102394398-b2fdd500-3fa7-11eb-87fe-25d65bfc3660.png">

Does it look good? If so, I am going to commit to the `rendition_issues` branch.

**Comment by tubesoft** [comment]
The solution is included in [this commit](https://github.com/IUBLibTech/newton_chymistry/pull/99).

**Comment by wehooper** [comment]
This has been corrected as we wanted.

**Comment by mdalmau** [comment]
Looks good on Carbon.
