### ISSUE TITLE
Folio & Page Image not responsive to smaller browser size

### ISSUE THREAD

**Issue by mdalmau** [IUBLibTech/newton_chymistry#93]
The folio numbering and page image link don’t move over from the center if you resize the window. So in a thin browser window, you can’t see them at all unless you scroll horizontally. Reported by Alex Wingate.

**Comment by mdalmau** [comment]
I think this may be related to something @tubesoft & @wehooper were working on with the catchwords and/or column layout.  Is it?  I'll look through the other issues to link them, if they are.

**Comment by tubesoft** [comment]
The solution is included in [this commit](https://github.com/IUBLibTech/newton_chymistry/pull/99). I can make further change if needed.

I did like:
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/17519127/105550390-55a82280-5ccf-11eb-8273-232e526d2c65.png">
<img width="646" alt="image" src="https://user-images.githubusercontent.com/17519127/105550448-6ce71000-5ccf-11eb-80b8-85ab0a37d16e.png">

**Comment by wehooper** [comment]
The alignment-on-resize problem has been fixed.

**Comment by mdalmau** [comment]
I am not sure what I should be reviewing here so I will ask @wehooper to verify on Carbon:
https://newton.dlib.indiana.edu/text/ALCH00091/normalized?highlight=Operationum%20Ordo#?#hit1&c=&m=&s=&cv=&xywh=-1625%2C-386%2C7749%2C7701
