### ISSUE TITLE
Manuscript Titles Showing Incorrectly 

### ISSUE THREAD

**Issue by mdalmau** [IUBLibTech/newton_chymistry#95]
There’s also an odd title at the top of the manuscript page (This is again ALCH00063, but it happens with other mss too) that I don’t think is what you actually want there. On the current site it’s the holding library and shelfmark. Reported by Alex Wingate. 

http://possum.dlib.indiana.edu:8197/text/ALCH00063/

![image009](https://user-images.githubusercontent.com/573273/95997259-9c010200-0e01-11eb-90a7-8671c2f9b2b2.jpg)

**Comment by mdalmau** [comment]
Related to #91

**Comment by tubesoft** [comment]
The solution is included in [this commit](https://github.com/IUBLibTech/newton_chymistry/pull/99).

**Comment by wehooper** [comment]
This has been corrected in the way we wanted.

**Comment by mdalmau** [comment]
This has been updated in Carbon.  Looks good!
